### ISSUE TITLE
hash Hamming distance use hex or binary, which one is good?

### ISSUE THREAD

**Issue by CC11001100** [bunchesofdonald/photohash#10]
hash Hamming distance use hex or binary, which one is good?
now:
```
def hash_distance(left_hash, right_hash):
    """Compute the hamming distance between two hashes"""
    if len(left_hash) != len(right_hash):
        raise ValueError('Hamming distance requires two strings of equal length')

    return sum(map(lambda x: 0 if x[0] == x[1] else 1, zip(left_hash, right_hash)))
```

i think:
```
def hash_distance(left_hash, right_hash):
    """Compute the hamming distance between two hashes"""
    if len(left_hash) != len(right_hash):
        raise ValueError('Hamming distance requires two strings of equal length')

    lh = format(int(left_hash, 16), '#b')
    rh = format(int(right_hash, 16), '#b')
    return sum(map(lambda x: 0 if x[0] == x[1] else 1, zip(lh, rh)))
```

**Comment by bunchesofdonald** [comment]
@CC11001100 You could certainly do it that way, there are a couple reasons I can think of not to:

1. The method is an implementation of [Hamming distance|https://en.wikipedia.org/wiki/Hamming_distance] which simply works on strings, so encoding logic into the method about what we expect the strings to contain seems wrong.

2. The output of all the hashing code is, in the end hexadecimal, so with the default implementation you have a max range of `0` to `len(left_hash)`, but if we converted those hashes to binary and then compared the range would be `0` to `len(left_hash) * 4` which I think would lead to more confusion about the similarity of the two hashes.
