### ISSUE TITLE
Dosen't seem to work at all..

### ISSUE THREAD

**Issue by davegri** [bunchesofdonald/photohash#5]
Steps to reproduce:

Download both images from here:
http://imgur.com/a/XJa8A

    In [6]: hash1 = photohash.average_hash('/home/david/Desktop/1.jpg')
    In [7]: hash2 = photohash.average_hash('/home/david/Desktop/2.jpg')
    In [8]: hash1
    Out[8]: 'ffffffbf00000000'
    In [9]: hash2
    Out[9]: 'ffffffbf00000000'
    In [10]: 

this isn't even a rare occurrence.. 
I tested this with a database of thousands of photos and many of them that look completely different created the exact same hash..

**Comment by bunchesofdonald** [comment]
I'm sorry you're having issues. I'll look into this today and see what I can find out. Thanks for reporting it!

**Comment by bunchesofdonald** [comment]
It looks like you're running into a hash collision. I'd recommend upping the size of your hash to 16, possibly more depending on your data set and how accurate you want it to be, unfortunately with this kind of thing there is some trial and error involved.

To do that, just pass `hash_size=16` as an argument to `average_hash`:

    hash1 = photohash.average_hash('/home/david/Desktop/1.jpg', hash_size=16)
    hash2 = photohash.average_hash('/home/david/Desktop/2.jpg', hash_size=16)

Doing this I get:

    hash1 = 'ffffffffffffffffffffffff9bfe32eb004d0000000000000000004000000000'
    hash2 = 'ffffffffffffffffffffffffffff43f800000000000000000000000000000000'

As to why this is the case, if you `average_hash` these two images with a `hash_size` of 8, this is the way the algorithm looks at the images:

#### flowers

```
# The pixel value (0-255, 0 = black, 255 = white) for each of the 64 pixels (hash size of 8, so 8 * 8 = 64).
pixels = [150, 148, 147, 141, 144, 149, 150, 147, 199, 174, 177, 176, 173, 150, 150, 156, 184, 157, 179, 194, 182, 171, 153, 146, 127, 123, 131, 149, 142, 147, 151, 139, 104, 97, 104, 97, 103, 104, 110, 117, 93, 100, 93, 91, 87, 108, 100, 97, 94, 99, 98, 94, 110, 112, 110, 109, 56, 64, 65, 75, 84, 79, 74, 90]  

# The sum of the values (8024) / the number of values (64).
average_pixel_value = 125.375

# The 'bits' are computed by looking at each pixel value, if it's greater than the average_pixel_value, it gets a 1, otherwise it gets a 0.
bits = '1111111111111111111111111011111100000000000000000000000000000000'
```

#### mountains

```
# The pixel value (0-255, 0 = black, 255 = white) for each of the 64 pixels (hash size of 8, so 8 * 8 = 64).
pixels = [203, 207, 210, 208, 205, 200, 194, 184, 222, 227, 232, 236, 240, 236, 231, 225, 158, 166, 186, 207, 220, 221, 217, 208, 132, 120, 134, 159, 154, 153, 142, 138, 112, 105, 99, 86, 75, 79, 81, 89, 82, 71, 60, 62, 57, 46, 53, 47, 51, 41, 38, 41, 24, 20, 23, 28, 39, 31, 32, 32, 11, 21, 24, 21]

# The sum of the values (7856) / the number of values (64).
average_pixel_value = 122.75

# The 'bits' are computed by looking at each pixel value, if it's greater than the average_pixel_value, it gets a 1, otherwise it gets a 0.
bits = '1111111111111111111111111011111100000000000000000000000000000000'
```

As you can see, they both compute to the same hash with a size of 8.

**Comment by bunchesofdonald** [comment]
And just because I think it's interesting, here are the actual scaled down versions of those images.

#### Hash size 8
![Flowers at hash size 8](http://chrispickett.me/media/photohash/flowers64.jpg)
![Mountains at hash size 8](http://chrispickett.me/media/photohash/mountains64.jpg)

#### Hash size 16
![Flowers at hash size 16](http://chrispickett.me/media/photohash/flowers256.jpg)
![Mountains at hash size 16](http://chrispickett.me/media/photohash/mountains256.jpg)

You can see why with a hash size of 8, the computer thinks they're similar images.
