### ISSUE TITLE
Exposing a richer API

### ISSUE THREAD

**Issue by lisandro52** [bunchesofdonald/photohash#6]
Hey! First of all, thanks for this library. It's simple, but it's what I was looking for after finding that a fork from this one (ImageHash) was useful but had too bloated dependencies (numpy+scipy).

Now that I'm using this one, I found that the already exposed methods (`is_look_alike` and `distance`) are great, but could be better.
**How?**
Both of those methods receive paths to images, which means that everytime you call them, you are loading both images to memory, calculating the hash and comparing them.
Something that would be awesome is that the library could also receive *hashes* to make the same calculations. Something like two new methods `hashes_are_look_alike` or `hashes_are_similar`, and `hashes_distance`.

**Comment by bunchesofdonald** [comment]
Thank you so much for the nice comments, I'm glad that it's useful!

Agreed, that would be a very good change, I'll work on this and hopefully have a release that you can use later today.

**Comment by bunchesofdonald** [comment]
It turned out to be easier than I expected. You can see the code changes here: https://github.com/bunchesofdonald/photohash/pull/7/ and I released version 0.4.0 to pypi.

**Comment by lisandro52** [comment]
Pretty quick, thanks! I'm at work right now, so I can't test it with my application but the changes are looking good from what I saw.
Thanks again for this. Are you still thinking about adding more hashing algorithms?

**Comment by bunchesofdonald** [comment]
It's on my list of things I'd like to do, but for my own personal projects average_hash has worked out pretty well, so there just hasn't been a lot of motivation.

**Comment by bunchesofdonald** [comment]
@lisandro52 I'm going to go ahead and close this out, feel free to re-open it if you found/find issues.
