### ISSUE TITLE
AttributeError: 'module' object has no attribute 'distance'

### ISSUE THREAD

**Issue by urwithajit9** [bunchesofdonald/photohash#9]
I have installed photohash using pip and when try to run photohash.distance() on two image, I found below error.
distance(image_path, other_image_path)
Throw error like:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'distance'

**Comment by bunchesofdonald** [comment]
Crap, I'm sorry @urwithajit9 , it looks like the main __init__.py wasn't importing the distance method, I fixed that and pushed it out as version 0.4.1 and it looks like it should fix your issue:

    $ pip install photohash==0.4.1
    Downloading/unpacking photohash==0.4.1
      Downloading Photohash-0.4.1.tar.gz
      ...
    Successfully installed photohash
    Cleaning up...
    $ python
    Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
    [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import photohash
    >>> photohash.distance
    <function distance at 0x106d5e848>

Let me know if you have more issues with this. If for some reason you can't update to 0.4.1, you _should_ be able to use 0.4.0 by doing:

    import photohash
    photohash.photohash.distance(...)

**Comment by bunchesofdonald** [comment]
Fixed by: https://github.com/bunchesofdonald/photohash/commit/1839a37a884e8c31cb94e661bd76f8125b0dfcb6
